config/routes.rb
<<<<<<< HEAD
SampleApp::Application.routes.draw do
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
=======
Depot::Application.routes.draw do
  get "user_blog/index"
  post 'store/add_to_cart'
  resources :products

>>>>>>> d21c5c2be118af4930b611b46ab9c7ac41298397

<<<<<<< HEAD

=======
  
>>>>>>> d21c5c2be118af4930b611b46ab9c7ac41298397

end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize
    @items = []
  end

  def add_product(product)
    current_item = @items.find {|item| item.product == product }
    if current_item
      current_item.increment_quantity
    else
      @items << CartItem.new(product)
    end
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product,:quantity

  def initialize(product)
    @product = product
    @quantity = 1
  end

  def increment_quantity
    @quantity += 1
  end

  def title
    @product.title
  end

  def price
    @product.price * @quantity
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title,:img_url
  validates_uniqueness_of :title

  validates_length_of :description,:minimum => 5,:maxmum=>500
  validates_numericality_of :price
  validate :price_must_be_at_least_a_cent

  validates_format_of :img_url,
                        :with=> %r{\.(gif|jpg|jpeg|png)$}i,
                        :multiline => true,
                        :message=>"img_url must be a url for gif,jpg,jpeg,png"

  private
  def price_must_be_at_least_a_cent
    errors.add(:price,"price must be at least 0.01")  if price.try(:<,0.01)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error("attempt to access invalid product #{params[:id]}")
      flash[:notice] = 'invalid id'
      redirect_to products_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description,:price, :img_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def add_to_cart
    @cart = find_cart
    product = Product.find(params[:id])
    @cart.add_product(product)
    # render('')
  rescue ActiveRecord::RecordNotFound
    logger.error("attempt to access invalid product #{params[:id]}")
    flash[:notice] = 'invalid id'
    redirect_to products_path
  end

  private
  def find_cart
    session[:cart] ||= Cart.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "About",'#' %></li>
      <li>
        <%= link_to "Contact", '#' %></li>
      <li>
        <a href="http://news.railstutorial.org/">News</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li>
              <%= link_to "Home",'#' %></li>
            <li>
              <%= link_to "Help",'#' %></li>
            <li>
              <%= link_to "Sign in", '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
  <title>Ruby on Rails Tutorial Sample App |
    <%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %></body>
  </div>

</html>
=======
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "scaffold" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
>>>>>>> d21c5c2be118af4930b611b46ab9c7ac41298397

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<p id="notice"><%= flash[:notice] %></p>
<table>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list-line-odd','list-line-even') %>">
          <td><%= image_tag product.img_url,:class=>"list-image" %> </td>
          <td class="list-description"> 
            <dl>
              <dt> <%= product.title %> </dt>
              <dd><%= truncate(product.description.gsub(/<.*?>/,''),:length=>80) %> </dd>
            </dl>
          </td>
          <td lass="list-actions">
            <%= link_to 'Show',product_path(product) %> <br/>
            <%= link_to 'Edit',edit_product_path(product) %> <br/>
            <%= link_to 'Destroy',product_path(product),method: :delete ,data:{confirm: 'Are you sure?'} %>
          </td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
  

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div style="border:1px solid #cccccc">
  <% render(:partical=> 'cart', :object => @cart) %>
</div>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price,:precision=>2,:unit=>'￥',:separator=>'.') %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @product.img_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= button_to 'Add to Cart',action: 'add_to_cart',controller: 'store',id: @product.id %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  The
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %></div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/store/_cart.html.erb
<div>
    <ul>
      <% render :partical => 'cart_item',:collections => @cart.items %>
    </ul>
</div>

app/views/store/_cart_item.html.erb
<li>

</li>

app/views/store/add_to_cart.html.erb
<div>
    <% @cart.items.each do |item| %>
      <span><%= item.title %></span> 
      X<span><%= item.quantity %> </span> 
      <span><%= number_to_currency(item.price,unit: '￥') %> </span>
    <% end -%>
</div>